// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tokens.Infrastructure.Persistence.Database;

namespace Tokens.Infrastructure.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200909072022_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tokens.Domain.Entities.AccessLogItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Accessor")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.ToTable("AccessLog");
                });

            modelBuilder.Entity("Tokens.Domain.Entities.Token", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedByDevice")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Tokens.Domain.Entities.AccessLogItem", b =>
                {
                    b.HasOne("Tokens.Domain.Entities.Token", null)
                        .WithMany("AccessLog")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
