name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v3
      - run: bash ./.ci/test.sh
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build Docker Image
        run: /bin/bash ./.ci/buildDockerImage.sh
        env:
          TAG: ${{ steps.vars.outputs.tag }}
      - name: Publish Docker Image
        run: /bin/bash ./.ci/publishDockerImage.sh
        env:
          TAG: ${{ steps.vars.outputs.tag }}
