name: Test

on:
  push:
    branches-ignore:
      - "main"
    tags-ignore:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - uses: actions/checkout@v2
      - run: bash ./.ci/test.sh
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./.ci/buildDockerImage.sh
